### ISSUE TITLE
Rendering issues and crash reported

### ISSUE THREAD

**Issue by agmathew** [quiver-dev/template-beat-em-up#110]
"Unfortunately every time when I run the project from the editor everything first seems fine but when I click on any of the menu items to start the game, both the game and the Godot editor totally freak out which this rendering bug:

https://i.imgur.com/HI6g6Z1.png

And then usually crashes.

I have tried it with both Beta4 and Beta3, same results. This issue does not appear when I just run the test_scenes.

I have seen this rendering issue appear randomly in earlier pre-alpha versions of Godot4, but not since then. I have never seen this appear in any of my Godot4 Alpha or Beta test projects or scene, although they are usually much smaller than your project."

From Reddit comment: https://www.reddit.com/r/godot/comments/yv5cgd/make_your_own_streets_of_rage_with_our_open/iwg61d6/

**Comment by eh-jogos** [comment]
@agmathew I traded some comments with the poster on reddit and we found out his GPU is a GeForce GTX 765M ([in this comment](https://www.reddit.com/r/godot/comments/yv5cgd/comment/iwm4x6h/?utm_source=share&utm_medium=web2x&context=3))

So the hypothesis that the problem is the video memory usage is quite plausible, and for reference, I searched for the release that of that GPU and it is some time in 2013, so we are probably looking at a pretty old notebook with hybrid graphics that uses this mobile GPU.

To make things faster I'm only cutting the "effects" textures in half for both the area and grenade attacks as this has already reduced the memory usage by almost 50%, from 2.64 GiB to 1.38GiB on GPU texture usage memory.

But if we have more time and budget maybe we could think of a system to split the level in smaller scenes and load them seamlessly, but I don't think this is a good time for it as ` load_threaded_request` still has [quite a few bugs](https://github.com/godotengine/godot/issues?q=is%3Aissue+is%3Aopen+load_threaded_request), I had noticed the wrong status report one, and then found the others.

I'm leaving this open for now though as I'll wait to see what our friend on reddit replies once he tests again, but besides what's written here I'm out of ideas.

What do you think? Do you think it's worth to try to instance tax man dynamically even if we don't split the stage is smaller scenes? 

I'm kinda worried that this will not give any result as either taxman's tscn will already be loaded and just waiting to be instanced, and thus the textutres already on the memory, or we might have hiccups trying to load the taxman's scene if we try to load it in the background and it's not ready when we need it.

**Comment by agmathew** [comment]
Let's just scale the effects textures by half for now and start with that. We can revisit the ```load_threaded_request``` once things have stabilized a little. The dynamic loading only really helps if we're unloading other things, otherwise we're just delaying the crash from the beginning to when the player reaches the Tax Man. It also makes me wonder if there's an opportunity for a more generalized solution where we make it easy to load and unload scenes in our templates.

**Comment by eh-jogos** [comment]
@agmathew The template already has a very simple "background loader" for loading the game scene while you are on start menu. 

For example, if you open the game and go to how to play and is reading the instructions there, chances are that when you click play you won't see the "loading bar" at the bottom and won't have to wait for it to finish loading, I only show that if the scene hasn't finished loading yet.

I think that can be reused in other projects, but whatever we do to split the level itself in smaller parts might be too specific.
